name: Registration_E2E_Test

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: ''

jobs:
  Registration_E2E_Test:
    runs-on: ubuntu-latest  # Specify Ubuntu as the runner
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven
          mvn --version

      - name: Setup xvfb for screen 0
        run: Xvfb :1 -screen 0 1600x1200x24 &

      - name: Execute Tests
        run: mvn -Dtest="${{ github.event.inputs.testsPath }}" test
        env:
          DISPLAY: :1
      - name: Tear down xvfb
        run: killall Xvfb

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit