name: Registration_E2E_Test

on:
  workflow_dispatch:
    inputs:
      testsPath:
        description: 'Path to Tests to be Executed'
        default: 'Automation.test.RegistrationTests'
      OSRun1:
        required: true
        default: 'Ubuntu'
        description: Please select the OS to run test1
        type: choice
        options:
          - windows
          - Ubuntu
      BrowserRun1:
        required: true
        default: 'chrome'
        description: Please select the browser to run test1
        type: choice
        options:
          - chrome
          - edge
      OSRun2:
        required: true
        default: 'windows'
        description: Please select the OS to run test1
        type: choice
        options:
          - Ubuntu
          - windows
      BrowserRun2:
        required: true
        default: 'edge'
        description: Please select the browser to run test1
        type: choice
        options:
          - chrome
          - edge

  pull_request:
    types:
      - opened
    branches:
      - 'main/**'
jobs:
  Registration_E2E_First_Test:
    runs-on: ${{ github.event.inputs.OSRun1 }}-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: mvn -DBrowserName="${{ github.event.inputs.BrowserRun1 }}" -Dtest="${{ github.event.inputs.testsPath }}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit

  Registration_E2E_Second_Test:
    runs-on: ${{ github.event.inputs.OSRun2 }}-latest
    permissions:
      checks: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Execute Tests
        run: mvn -DBrowserName="${{ github.event.inputs.BrowserRun2 }}" -DHeadLessBrowsing="false" -Dtest="${{ github.event.inputs.testsPath }}" test

      - name: Publish Report
        continue-on-error: true
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Report
          path: 'target/surefire-reports/TEST-*.xml'
          reporter: java-junit